version: "3.9"
services:

  personal_website_client:
    container_name: personal_website_client
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app
    command: npm run dev
